name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/install@v0.1
      with:
        crate: cargo-readme
        version: latest
        use-tool-cache: true
    - name: Readme
      run: cargo readme > README.md && git diff --exit-code
    - name: Format
      run: cargo fmt --all -- --check
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run loom tests
      run: RUSTFLAGS="--cfg loom" cargo test --release loom_tests
      
